version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-flask-app .
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker tag my-flask-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-flask-app:latest
      - docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-flask-app:latest
artifacts:
  files:
    - '**/*'
